In [1]:
import tensorflow as tf
from tensorflow import keras
from keras import layers
from keras.models import Sequential
from keras.layers import Dense, Activation
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
print(tf.__version__)
print(keras.__version__)

2.2.0-rc4
2.3.0-tf


In [2]:
NLPdata = pd.read_csv('nlpdata.csv')
NLPdata = NLPdata.to_numpy()
#X1train = NLParray[:,0].reshape((-1,1))
#X2train = NLParray[:,1].reshape((-1,1))
#Ytrain = NLParray[:,2]
#print(X1train)
#print(X2train)
#print(Ytrain)

#NLPdata = pd.read_csv('nlpdata.csv')
#NLPdata = NLPdata.to_numpy() 

##  Original testing

In [3]:
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=1)) 
model.add(Dense(28, activation='relu')) 
model.add(Dense(10, activation='softmax'))
model.compile(loss='mean_squared_error', optimizer='adam')

In [4]:
import sklearn.model_selection as model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(NLPdata[:,0], NLPdata[:,2], train_size=0.75,test_size=0.25, random_state=101)
print ("X_train: ", X_train)
print ("y_train: ", y_train)
print ("X_test: ", X_test)
print ("y_test: ", y_test)

X_train:  [4. 4. 5. 4. 4. 4. 4. 4. 3. 1. 4. 4. 3. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 3.
 1. 2. 3. 1. 4. 4. 6. 4. 4. 1. 4. 4. 1. 4. 4. 2. 3. 4. 4. 2. 1. 5. 3. 2.
 5. 4. 4. 2. 4. 4. 1. 1. 4. 4. 2. 4. 2. 3. 2. 4. 4. 4. 4. 4. 4. 3. 6. 3.
 3. 4. 3. 4. 2. 5. 2. 1. 4. 1. 4. 3. 4. 1. 4. 1. 3. 1. 3. 3. 3. 4. 4. 5.
 4. 4. 3. 4. 4. 4. 4. 4. 2. 2. 4. 4. 4. 4. 4. 1. 2. 3. 2. 4. 4. 4. 1. 4.
 5. 1. 5. 4. 4. 2. 4. 3. 2. 4. 3. 3. 4. 1. 3. 5. 3. 2. 3. 5. 4. 4. 4. 4.
 3. 1. 4. 3. 2. 2. 4. 2. 4. 4. 4. 4. 2. 4. 4. 3. 4. 1. 4. 4. 4. 3. 4. 4.
 2. 2. 2. 4. 4. 3. 4. 3. 4. 4. 2. 2. 4. 4. 5. 1. 2. 4. 4. 2. 2. 4. 3. 4.
 4. 4. 5. 4. 2. 3. 1. 4. 3. 4. 4. 3. 2. 4. 1. 4. 4. 2. 4. 4. 4. 4. 4. 4.
 2. 2. 4. 2. 4. 4. 4. 5. 4. 3. 4. 4. 3. 2. 1. 3. 4. 4. 3. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 1. 4. 4. 3. 1. 3. 4. 4. 4. 4. 4. 4. 2. 4. 2. 3.
 3. 4. 2. 4. 4. 4. 4. 4. 1.]
y_train:  [ 0.05        0.15918367  0.          0.16241497  0.          0.15642857
 -0.09270833 -0.06452991  0.01012397  0.43333333 -0.02916667  0.109375
  0.

In [5]:
X_train = X_train.reshape(-1,1)
y_train = y_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)
y_test = y_test.reshape(-1,1)

print ("X_train: ", X_train)
print ("y_train: ", y_train)
print ("X_test: ", X_test)
print ("y_test: ", y_test)

X_train:  [[4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [4.]
 [4.]
 [6.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [2.]
 [3.]
 [4.]
 [4.]
 [2.]
 [1.]
 [5.]
 [3.]
 [2.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [1.]
 [1.]
 [4.]
 [4.]
 [2.]
 [4.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [6.]
 [3.]
 [3.]
 [4.]
 [3.]
 [4.]
 [2.]
 [5.]
 [2.]
 [1.]
 [4.]
 [1.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [1.]
 [3.]
 [1.]
 [3.]
 [3.]
 [3.]
 [4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [1.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [1.]
 [4.]
 [5.]
 [1.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [3.]
 [2.]
 [4.]
 [3.]
 [3.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [2.]
 [3.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [3.]
 [2.]
 [2.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [4.]
 [4.]


In [6]:
model.fit(X_train, y_train, batch_size=30, epochs=20, verbose=1, validation_data=(X_test, y_test))

Epoch 1/20
10/10 [==============================] - 0s 17ms/step - loss: 0.0408 - val_loss: 0.0431
Epoch 2/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0400 - val_loss: 0.0429
Epoch 3/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 4/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 5/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 6/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 7/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 8/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 9/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 10/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 11/20
10/10 

In [7]:
score = model.evaluate(X_test, y_test, batch_size=30)

4/4 [==============================] - 0s 2ms/step - loss: 0.0428


In [8]:
model.predict(X_test, batch_size=30)
model.predict_classes(X_test, batch_size=30)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([7, 7, 3, 7, 3, 7, 3, 7, 7, 3, 7, 7, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7,
       3, 3, 3, 3, 3, 7, 3, 7, 7, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3,
       3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 3,
       3, 7, 3, 7, 7, 3, 7, 3, 3, 7, 7, 7, 3, 3, 3, 3, 7, 3, 3, 3, 7, 7,
       7, 3, 7, 3])

In [9]:
model.predict(y_test, batch_size=30)
model.predict_classes(y_test, batch_size=30)

array([7, 2, 7, 1, 7, 1, 6, 7, 1, 7, 2, 7, 1, 7, 6, 7, 7, 7, 7, 6, 7, 1,
       7, 6, 7, 7, 7, 2, 7, 7, 1, 7, 7, 7, 1, 1, 7, 7, 7, 2, 7, 6, 7, 6,
       7, 6, 1, 2, 7, 1, 6, 7, 1, 6, 2, 2, 6, 7, 7, 7, 2, 2, 7, 7, 7, 7,
       7, 7, 7, 2, 1, 6, 1, 6, 7, 1, 6, 2, 7, 1, 6, 2, 2, 1, 1, 6, 6, 2,
       1, 2, 2, 1])

In [10]:
#Predict values test objects
X_new = X_test
y_proba = model.predict(X_new).round(2) # do I need the .round(2)?
print(y_proba)

[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0

In [11]:
# now let's try a prediction based on Q40

X_train2, X_test2, y_train, y_test = model_selection.train_test_split(NLPdata[:,1], NLPdata[:,2], train_size=0.75,test_size=0.25, random_state=101)
print ("X_train: ", X_train)
print ("y_train: ", y_train)
print ("X_test: ", X_test)
print ("y_test: ", y_test)

X_train:  [[4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [4.]
 [4.]
 [6.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [2.]
 [3.]
 [4.]
 [4.]
 [2.]
 [1.]
 [5.]
 [3.]
 [2.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [1.]
 [1.]
 [4.]
 [4.]
 [2.]
 [4.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [6.]
 [3.]
 [3.]
 [4.]
 [3.]
 [4.]
 [2.]
 [5.]
 [2.]
 [1.]
 [4.]
 [1.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [1.]
 [3.]
 [1.]
 [3.]
 [3.]
 [3.]
 [4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [1.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [1.]
 [4.]
 [5.]
 [1.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [3.]
 [2.]
 [4.]
 [3.]
 [3.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [2.]
 [3.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [3.]
 [2.]
 [2.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [4.]
 [4.]


X_train2 = X_train2.reshape(-1,1)
y_train = y_train.reshape(-1,1)
X_test2 = X_test2.reshape(-1,1)
y_test = y_test.reshape(-1,1)

print ("X_train2: ", X_train2)
print ("y_train: ", y_train)
print ("X_test2: ", X_test2)
print ("y_test: ", y_test)

In [12]:
model.fit(X_train2, y_train, batch_size=30, epochs=20, verbose=1, validation_data=(X_test2, y_test))

Epoch 1/20
10/10 [==============================] - 0s 12ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 2/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 3/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 4/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 5/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 6/20
10/10 [==============================] - 0s 6ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 7/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 8/20
10/10 [==============================] - 0s 8ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 9/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 10/20
10/10 [==============================] - 0s 7ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 11/20
10/10 

In [13]:
score = model.evaluate(X_test2, y_test, batch_size=30)

4/4 [==============================] - 0s 2ms/step - loss: 0.0428


In [14]:
model.predict(X_test2, batch_size=30)
model.predict_classes(X_test2, batch_size=30)

array([1, 4, 1, 5, 1, 4, 1, 4, 5, 1, 1, 4, 4, 1, 1, 4, 4, 1, 1, 4, 5, 4,
       1, 1, 4, 4, 1, 5, 4, 1, 4, 5, 1, 1, 1, 1, 1, 1, 4, 5, 4, 1, 4, 4,
       1, 5, 4, 1, 5, 1, 1, 1, 1, 4, 4, 1, 5, 4, 4, 4, 1, 4, 5, 5, 1, 4,
       4, 1, 1, 4, 5, 4, 4, 4, 4, 1, 1, 4, 4, 5, 1, 5, 4, 4, 4, 1, 1, 1,
       1, 4, 4, 5])

In [15]:
model.predict(y_test, batch_size=30)
model.predict_classes(y_test, batch_size=30)

array([1, 4, 1, 8, 1, 8, 5, 1, 8, 1, 2, 1, 8, 1, 6, 1, 1, 1, 1, 5, 1, 8,
       1, 6, 1, 1, 1, 5, 1, 1, 8, 1, 1, 1, 8, 8, 1, 1, 1, 4, 1, 6, 1, 6,
       1, 6, 5, 8, 1, 8, 6, 1, 8, 6, 4, 4, 5, 1, 1, 1, 8, 4, 1, 1, 1, 1,
       1, 1, 1, 2, 8, 6, 8, 6, 1, 8, 6, 4, 1, 8, 6, 5, 5, 1, 8, 5, 5, 8,
       8, 5, 4, 8])

In [16]:
#Predict values test objects
X_new = X_test2
y_proba = model.predict(X_new) # do I need the .round(2)?
print(y_proba)

[[0.09997921 0.10032825 0.10000892 0.0997367  0.09975554 0.10000326
  0.10008276 0.10019363 0.09991469 0.09999702]
 [0.09994226 0.09995889 0.10003504 0.10007003 0.10007544 0.09998531
  0.09989804 0.10002753 0.10005434 0.09995313]
 [0.09997921 0.10032825 0.10000892 0.0997367  0.09975554 0.10000326
  0.10008276 0.10019363 0.09991469 0.09999702]
 [0.09994822 0.09962972 0.10006044 0.10015477 0.09997173 0.10018791
  0.10014421 0.09986448 0.09993964 0.10009894]
 [0.09997921 0.10032825 0.10000892 0.0997367  0.09975554 0.10000326
  0.10008276 0.10019363 0.09991469 0.09999702]
 [0.09994226 0.09995889 0.10003504 0.10007003 0.10007544 0.09998531
  0.09989804 0.10002753 0.10005434 0.09995313]
 [0.09997921 0.10032825 0.10000892 0.0997367  0.09975554 0.10000326
  0.10008276 0.10019363 0.09991469 0.09999702]
 [0.09994226 0.09995889 0.10003504 0.10007003 0.10007544 0.09998531
  0.09989804 0.10002753 0.10005434 0.09995313]
 [0.09994822 0.09962972 0.10006044 0.10015477 0.09997173 0.10018791
  0.10014421

## Testing round 2,  12/28/2020

In [17]:
NLPdata = pd.read_csv('nlpdata.csv')
NLPdata = NLPdata.to_numpy()

In [18]:
model = Sequential()
model.add(Dense(20, activation='relu', input_dim=1)) 
#model.add(Dense(28, activation='relu')) 
model.add(Dense(10, activation='softmax'))
model.compile(loss='mean_squared_error', optimizer='adam')

In [19]:
import sklearn.model_selection as model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(NLPdata[:,0], NLPdata[:,2], train_size=0.75,test_size=0.25, random_state=101)
print ("X_train: ", X_train)
print ("y_train: ", y_train)
print ("X_test: ", X_test)
print ("y_test: ", y_test)

X_train:  [4. 4. 5. 4. 4. 4. 4. 4. 3. 1. 4. 4. 3. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 3.
 1. 2. 3. 1. 4. 4. 6. 4. 4. 1. 4. 4. 1. 4. 4. 2. 3. 4. 4. 2. 1. 5. 3. 2.
 5. 4. 4. 2. 4. 4. 1. 1. 4. 4. 2. 4. 2. 3. 2. 4. 4. 4. 4. 4. 4. 3. 6. 3.
 3. 4. 3. 4. 2. 5. 2. 1. 4. 1. 4. 3. 4. 1. 4. 1. 3. 1. 3. 3. 3. 4. 4. 5.
 4. 4. 3. 4. 4. 4. 4. 4. 2. 2. 4. 4. 4. 4. 4. 1. 2. 3. 2. 4. 4. 4. 1. 4.
 5. 1. 5. 4. 4. 2. 4. 3. 2. 4. 3. 3. 4. 1. 3. 5. 3. 2. 3. 5. 4. 4. 4. 4.
 3. 1. 4. 3. 2. 2. 4. 2. 4. 4. 4. 4. 2. 4. 4. 3. 4. 1. 4. 4. 4. 3. 4. 4.
 2. 2. 2. 4. 4. 3. 4. 3. 4. 4. 2. 2. 4. 4. 5. 1. 2. 4. 4. 2. 2. 4. 3. 4.
 4. 4. 5. 4. 2. 3. 1. 4. 3. 4. 4. 3. 2. 4. 1. 4. 4. 2. 4. 4. 4. 4. 4. 4.
 2. 2. 4. 2. 4. 4. 4. 5. 4. 3. 4. 4. 3. 2. 1. 3. 4. 4. 3. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 1. 4. 4. 3. 1. 3. 4. 4. 4. 4. 4. 4. 2. 4. 2. 3.
 3. 4. 2. 4. 4. 4. 4. 4. 1.]
y_train:  [ 0.05        0.15918367  0.          0.16241497  0.          0.15642857
 -0.09270833 -0.06452991  0.01012397  0.43333333 -0.02916667  0.109375
  0.

In [20]:
X_train = X_train.reshape(-1,1)
y_train = y_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)
y_test = y_test.reshape(-1,1)

print ("X_train: ", X_train)
print ("y_train: ", y_train)
print ("X_test: ", X_test)
print ("y_test: ", y_test)

X_train:  [[4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [4.]
 [4.]
 [6.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [2.]
 [3.]
 [4.]
 [4.]
 [2.]
 [1.]
 [5.]
 [3.]
 [2.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [1.]
 [1.]
 [4.]
 [4.]
 [2.]
 [4.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [6.]
 [3.]
 [3.]
 [4.]
 [3.]
 [4.]
 [2.]
 [5.]
 [2.]
 [1.]
 [4.]
 [1.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [1.]
 [3.]
 [1.]
 [3.]
 [3.]
 [3.]
 [4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [1.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [1.]
 [4.]
 [5.]
 [1.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [3.]
 [2.]
 [4.]
 [3.]
 [3.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [2.]
 [3.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [3.]
 [2.]
 [2.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [4.]
 [4.]


In [21]:
model.fit(X_train, y_train, batch_size=10, epochs=10, verbose=1, validation_data=(X_test, y_test))

Epoch 1/10
28/28 [==============================] - 0s 5ms/step - loss: 0.0444 - val_loss: 0.0450
Epoch 2/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0414 - val_loss: 0.0437
Epoch 3/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0405 - val_loss: 0.0432
Epoch 4/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0401 - val_loss: 0.0430
Epoch 5/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0399 - val_loss: 0.0429
Epoch 6/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0399 - val_loss: 0.0428
Epoch 7/10
28/28 [==============================] - 0s 4ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 8/10
28/28 [==============================] - 0s 5ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 9/10
28/28 [==============================] - 0s 5ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 10/10
28/28 [==============================] - 0s 4ms/step - loss: 0.0398 - val_loss: 0.0428


In [22]:
model.evaluate(X_test, y_test) #, batch_size=30

3/3 [==============================] - 0s 2ms/step - loss: 0.0428


0.04280076175928116

In [23]:
model.predict(X_test, batch_size=30)
model.predict_classes(X_test, batch_size=30)

array([4, 4, 7, 4, 7, 4, 7, 4, 4, 7, 4, 4, 7, 7, 7, 7, 7, 7, 7, 4, 4, 4,
       7, 7, 7, 7, 7, 4, 7, 4, 4, 7, 7, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 7,
       7, 7, 7, 7, 7, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 4, 4, 4, 7,
       7, 4, 7, 4, 4, 7, 4, 7, 7, 4, 4, 4, 7, 7, 7, 7, 4, 7, 7, 7, 4, 4,
       4, 7, 4, 7])

In [24]:
model.predict(y_test, batch_size=30)
model.predict_classes(y_test, batch_size=30)

array([4, 9, 9, 9, 4, 9, 9, 9, 9, 4, 9, 4, 9, 9, 5, 9, 9, 4, 4, 9, 4, 9,
       4, 5, 4, 4, 9, 9, 9, 4, 9, 4, 9, 9, 9, 9, 4, 9, 9, 9, 4, 5, 4, 5,
       4, 5, 9, 9, 4, 9, 5, 4, 9, 5, 9, 9, 9, 4, 4, 9, 9, 9, 9, 4, 9, 4,
       9, 4, 4, 9, 9, 5, 9, 5, 4, 9, 5, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9])

In [25]:
#Predict values test objects
X_new = X_test
y_proba = model.predict(X_new) # do I need the .round(2)?
print(y_proba)

[[0.10048839 0.10081188 0.09958655 0.09935687 0.10159941 0.10071493
  0.10037519 0.09771206 0.09798554 0.10136919]
 [0.10048839 0.10081188 0.09958655 0.09935687 0.10159941 0.10071493
  0.10037519 0.09771206 0.09798554 0.10136919]
 [0.09960989 0.09949062 0.09992879 0.10024745 0.09887737 0.09886299
  0.09964871 0.10390861 0.10080179 0.09862378]
 [0.10130636 0.10208189 0.09917866 0.0984079  0.10432606 0.10253246
  0.10103885 0.09182316 0.09518383 0.10412084]
 [0.09960989 0.09949062 0.09992879 0.10024745 0.09887737 0.09886299
  0.09964871 0.10390861 0.10080179 0.09862378]
 [0.10048839 0.10081188 0.09958655 0.09935687 0.10159941 0.10071493
  0.10037519 0.09771206 0.09798554 0.10136919]
 [0.09960989 0.09949062 0.09992879 0.10024745 0.09887737 0.09886299
  0.09964871 0.10390861 0.10080179 0.09862378]
 [0.10130636 0.10208189 0.09917866 0.0984079  0.10432606 0.10253246
  0.10103885 0.09182316 0.09518383 0.10412084]
 [0.10048839 0.10081188 0.09958655 0.09935687 0.10159941 0.10071493
  0.10037519

In [26]:
print(len(y_proba))

92


In [27]:
# now let's try a prediction based on Q40

X_train2, X_test2, y_train2, y_test2 = model_selection.train_test_split(NLPdata[:,1], NLPdata[:,2], train_size=0.75,test_size=0.25, random_state=101)
print ("X_train: ", X_train)
print ("y_train: ", y_train)
print ("X_test: ", X_test)
print ("y_test: ", y_test)

X_train:  [[4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [4.]
 [4.]
 [6.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [1.]
 [4.]
 [4.]
 [2.]
 [3.]
 [4.]
 [4.]
 [2.]
 [1.]
 [5.]
 [3.]
 [2.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [1.]
 [1.]
 [4.]
 [4.]
 [2.]
 [4.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [6.]
 [3.]
 [3.]
 [4.]
 [3.]
 [4.]
 [2.]
 [5.]
 [2.]
 [1.]
 [4.]
 [1.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [1.]
 [3.]
 [1.]
 [3.]
 [3.]
 [3.]
 [4.]
 [4.]
 [5.]
 [4.]
 [4.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]
 [1.]
 [2.]
 [3.]
 [2.]
 [4.]
 [4.]
 [4.]
 [1.]
 [4.]
 [5.]
 [1.]
 [5.]
 [4.]
 [4.]
 [2.]
 [4.]
 [3.]
 [2.]
 [4.]
 [3.]
 [3.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [2.]
 [3.]
 [5.]
 [4.]
 [4.]
 [4.]
 [4.]
 [3.]
 [1.]
 [4.]
 [3.]
 [2.]
 [2.]
 [4.]
 [2.]
 [4.]
 [4.]
 [4.]
 [4.]
 [2.]
 [4.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [4.]
 [4.]


In [28]:
model.fit(X_train2, y_train2, batch_size=10, epochs=10, verbose=1, validation_data=(X_test2, y_test))

Epoch 1/10
28/28 [==============================] - 0s 5ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 2/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 3/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 4/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 5/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 6/10
28/28 [==============================] - 0s 4ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 7/10
28/28 [==============================] - 0s 4ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 8/10
28/28 [==============================] - 0s 3ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 9/10
28/28 [==============================] - 0s 8ms/step - loss: 0.0398 - val_loss: 0.0428
Epoch 10/10
28/28 [==============================] - 0s 11ms/step - loss: 0.0398 - val_loss: 0.0428


In [29]:
model.evaluate(X_test2, y_test2, batch_size=10)

10/10 [==============================] - 0s 1ms/step - loss: 0.0428


0.04280411824584007

In [30]:
model.predict(X_test2, batch_size=10)
model.predict_classes(X_test2, batch_size=10)

array([4, 9, 4, 7, 4, 9, 4, 9, 7, 4, 4, 9, 9, 4, 4, 9, 9, 4, 4, 9, 7, 7,
       4, 4, 7, 7, 4, 7, 9, 4, 9, 1, 4, 4, 4, 4, 4, 4, 9, 7, 9, 4, 9, 9,
       4, 7, 9, 4, 1, 4, 4, 4, 4, 9, 9, 4, 7, 7, 7, 9, 4, 9, 7, 7, 4, 9,
       9, 4, 4, 9, 7, 9, 9, 7, 9, 4, 4, 9, 9, 7, 4, 7, 9, 9, 9, 4, 4, 4,
       4, 9, 7, 7])

In [31]:
model.predict(y_test2, batch_size=10)
model.predict_classes(y_test2, batch_size=10)

array([4, 9, 9, 9, 4, 9, 5, 9, 9, 4, 9, 4, 9, 4, 2, 4, 9, 4, 4, 9, 4, 9,
       4, 2, 4, 4, 9, 9, 4, 4, 9, 4, 9, 4, 9, 9, 4, 4, 9, 9, 4, 5, 4, 5,
       4, 2, 9, 9, 4, 9, 5, 4, 9, 5, 9, 9, 5, 4, 4, 9, 9, 9, 4, 4, 4, 4,
       4, 4, 4, 9, 9, 2, 9, 2, 4, 9, 5, 9, 4, 9, 5, 9, 9, 9, 9, 5, 5, 9,
       9, 9, 9, 9])

In [32]:
#Predict values test objects
X_new = X_test2
y_proba = model.predict(X_new) # do I need the .round(2)?
print(y_proba)

[[0.10171172 0.10240626 0.0999556  0.1001334  0.10287727 0.10161135
  0.10068144 0.08963215 0.09853414 0.10245668]
 [0.09985018 0.0992253  0.10083149 0.09952573 0.10152185 0.10302215
  0.10120422 0.091053   0.09977868 0.10398736]
 [0.10171172 0.10240626 0.0999556  0.1001334  0.10287727 0.10161135
  0.10068144 0.08963215 0.09853414 0.10245668]
 [0.0989629  0.0985764  0.10003351 0.10033737 0.09750503 0.09817898
  0.09923381 0.10880693 0.10137435 0.09699067]
 [0.10171172 0.10240626 0.0999556  0.1001334  0.10287727 0.10161135
  0.10068144 0.08963215 0.09853414 0.10245668]
 [0.09985018 0.0992253  0.10083149 0.09952573 0.10152185 0.10302215
  0.10120422 0.091053   0.09977868 0.10398736]
 [0.10171172 0.10240626 0.0999556  0.1001334  0.10287727 0.10161135
  0.10068144 0.08963215 0.09853414 0.10245668]
 [0.09985018 0.0992253  0.10083149 0.09952573 0.10152185 0.10302215
  0.10120422 0.091053   0.09977868 0.10398736]
 [0.0989629  0.0985764  0.10003351 0.10033737 0.09750503 0.09817898
  0.09923381

In [ ]:
#Predict values test objects
X_new = X_test2
y_proba = model.predict(X_new).round(2)
print(y_proba)